#!/bin/bash
set -e

# set up ssh for github
mkdir -p ~/.ssh
echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
chmod 400 ~/.ssh/id_rsa
ssh-keyscan github.com >> ~/.ssh/known_hosts

# clone the *wiki* repo
mkdir -p ~/wiki
cd ~/wiki
git clone git@github.com:brigand/wiki-chat.wiki.git .

ls

