#!/bin/bash

mkdir -p ~/wiki
mkdir -p ~/.ssh
cd ~/wiki
echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
cat ~/.ssh/id_rsa
ssh-keyscan github.com >> ~/.ssh/known_hosts
git config --global user.name "YOUR NAME"
git clone git@github.com:brigand/wiki-chat.wiki.git
ls

