#!/bin/bash
set -e

# clone the *wiki* repo
mkdir -p ~/wiki
cd ~/wiki

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

git clone https://$TOKEN:x-oauth-basic@github.com/brigand/wiki-chat.wiki.git .
touch Chat.md
echo "" >> Chat.md
echo "$1" >> Chat.md
git add Chat.md
git commit -m "$1"
git push origin master >/dev/null 2>&1

